# Generated by Django 6.0.1 on 2026-06-22 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_clinicbookingsettings_no_show_after'),
        ('secretary', '0001_billing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(help_text='Auto-generated unique request number (e.g. PR-2026-000001).', max_length=30, unique=True, verbose_name='رقم الطلب')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الطلب')),
                ('category', models.CharField(choices=[('CLINIC', 'العيادة'), ('STAFF', 'الطاقم'), ('GENERAL', 'عام')], default='CLINIC', max_length=20, verbose_name='الفئة')),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض')], default='PENDING', max_length=20, verbose_name='الحالة')),
                ('note', models.TextField(blank=True, help_text="Secretary's optional justification for the purchase (the 'why'), shown to the owner.", verbose_name='سبب الطلب')),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Sum of line item totals — recomputed on change.', max_digits=10, verbose_name='الإجمالي')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('owner_note', models.TextField(blank=True, help_text="The owner's note on approval/rejection — visible to the secretary.", verbose_name='ملاحظة المالك')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='clinics.clinic', verbose_name='العيادة')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='مقدّم الطلب')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='روجع بواسطة')),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('total', models.DecimalField(decimal_places=2, help_text='quantity × unit_price — computed on save.', max_digits=10, verbose_name='الإجمالي')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='secretary.purchaserequest', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'Purchase Request Item',
                'verbose_name_plural': 'Purchase Request Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['clinic', 'status'], name='prq_clinic_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['clinic', 'created_at'], name='prq_clinic_date_idx'),
        ),
    ]
