# Generated by Django 6.0.1 on 2026-03-12 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicComplianceSettings',
            fields=[
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='compliance_settings', serialize=False, to='clinics.clinic')),
                ('score_increment_per_no_show', models.PositiveIntegerField(default=1)),
                ('score_threshold_block', models.PositiveIntegerField(default=3, help_text='Score at which patient is blocked.')),
                ('max_score', models.PositiveIntegerField(default=5)),
                ('auto_forgive_enabled', models.BooleanField(default=False)),
                ('auto_forgive_after_days', models.PositiveIntegerField(blank=True, help_text='Days without violation to auto-forgive.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Clinic Compliance Settings',
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('NO_SHOW', 'No Show'), ('MANUAL_WAIVER', 'Manual Waiver'), ('AUTO_FORGIVENESS', 'Auto Forgiveness')], max_length=50)),
                ('score_change', models.IntegerField(help_text='Change in bad_score. Can be positive (penalty) or negative (forgiveness).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_events', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_events', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_events', to='patients.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PatientClinicCompliance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bad_score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('WARNED', 'WARNED'), ('BLOCKED', 'BLOCKED')], default='OK', max_length=20)),
                ('last_violation_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_forgiven_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='clinics.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_compliances', to='patients.patientprofile')),
            ],
            options={
                'verbose_name_plural': 'Patient Clinic Compliances',
                'unique_together': {('clinic', 'patient')},
            },
        ),
    ]
