# Generated by Django 6.0.1 on 2026-03-02 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('clinic_name', models.CharField(help_text='Pre-assigned clinic name', max_length=255)),
                ('phone', models.CharField(default='', help_text='Normalized phone of the intended owner (059/056 format)', max_length=20)),
                ('national_id', models.CharField(default='', help_text='9-digit national ID of the intended owner', max_length=9)),
                ('plan_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', help_text='Subscription plan granted to the clinic.', max_length=10)),
                ('subscription_expires_at', models.DateTimeField(help_text='When the subscription granted by this code expires.')),
                ('max_doctors', models.PositiveIntegerField(default=2, help_text='Maximum number of doctors allowed under this subscription.')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry date. Leave blank for no expiry.', null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clinic Activation Code',
                'verbose_name_plural': 'Clinic Activation Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MAIN_DOCTOR', 'Main Doctor'), ('DOCTOR', 'Doctor'), ('SECRETARY', 'Secretary')], max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Clinic Staff',
                'verbose_name_plural': 'Clinic Staff',
            },
        ),
        migrations.CreateModel(
            name='ClinicSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('max_doctors', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clinic Subscription',
                'verbose_name_plural': 'Clinic Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='ClinicVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('owner_email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('clinic_phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('clinic_email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clinic Verification',
                'verbose_name_plural': 'Clinic Verifications',
            },
        ),
        migrations.CreateModel(
            name='ClinicWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic Working Hours',
                'verbose_name_plural': 'Clinic Working Hours',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='accounts.city')),
                ('main_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_clinic', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
