# Generated by Django 6.0.1 on 2026-02-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0002 doctor_intake_question_dated_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='clinics', to='doctors.specialty'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='clinicactivationcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiry date. Leave blank for no expiry.', null=True),
        ),
        migrations.AddField(
            model_name='clinicactivationcode',
            name='national_id',
            field=models.CharField(default='', help_text='9-digit national ID of the intended owner', max_length=9),
        ),
        migrations.AddField(
            model_name='clinicactivationcode',
            name='phone',
            field=models.CharField(default='', help_text='Normalized phone of the intended owner (059/056 format)', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
