# Generated by Django 6.0.1 on 2026-03-03 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='clinics', to='doctors.specialty'),
        ),
        migrations.AddField(
            model_name='clinicactivationcode',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_activation_used', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicactivationcode',
            name='used_by_clinic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_code', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='clinicstaff',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicstaff',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='clinicstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_employments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicsubscription',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='clinicverification',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='clinicworkinghours',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='clinics.clinic'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicstaff',
            unique_together={('clinic', 'user')},
        ),
        migrations.AddConstraint(
            model_name='clinicworkinghours',
            constraint=models.UniqueConstraint(fields=('clinic', 'weekday', 'start_time', 'end_time'), name='unique_clinic_working_hours'),
        ),
    ]
