# Generated by Django 6.0.1 on 2026-03-11 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDoctorIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, help_text='Standardized phone number being onboarded.', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pending Doctor Identity',
                'verbose_name_plural': 'Pending Doctor Identities',
            },
        ),
        migrations.AlterUniqueTogether(
            name='clinicstaff',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clinicstaff',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='When set, indicates this membership was revoked. Revoked memberships do not block re-invitation.', null=True),
        ),
        migrations.AddConstraint(
            model_name='clinicstaff',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('clinic', 'user'), name='unique_active_staff_per_clinic'),
        ),
        migrations.AddField(
            model_name='pendingdoctoridentity',
            name='created_by_invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_identity_lock', to='clinics.clinicinvitation'),
        ),
    ]
