# Generated by Django 6.0.1 on 2026-03-17 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicactivationcode',
            name='max_secretaries',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of secretaries allowed under this subscription.'),
        ),
        migrations.AddField(
            model_name='clinicactivationcode',
            name='plan_name',
            field=models.CharField(choices=[('SMALL', 'صغير'), ('MEDIUM', 'متوسط'), ('ENTERPRISE', 'مؤسسة')], default='SMALL', help_text='Plan tier (capacity) granted to the clinic.', max_length=20),
        ),
        migrations.AddField(
            model_name='clinicsubscription',
            name='activated_by',
            field=models.ForeignKey(blank=True, help_text='Admin who last activated/extended this subscription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicsubscription',
            name='max_secretaries',
            field=models.PositiveIntegerField(default=1, help_text='Override capacity; 0 = unlimited. Auto-set from plan_name if left at default.'),
        ),
        migrations.AddField(
            model_name='clinicsubscription',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal admin notes (billing, support, etc.)'),
        ),
        migrations.AddField(
            model_name='clinicsubscription',
            name='plan_name',
            field=models.CharField(choices=[('SMALL', 'صغير'), ('MEDIUM', 'متوسط'), ('ENTERPRISE', 'مؤسسة')], default='SMALL', help_text='Plan tier that determines doctor/secretary capacity.', max_length=20),
        ),
        migrations.AddField(
            model_name='clinicsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clinicactivationcode',
            name='plan_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', help_text='Subscription billing period granted to the clinic.', max_length=10),
        ),
        migrations.AlterField(
            model_name='clinicsubscription',
            name='max_doctors',
            field=models.PositiveIntegerField(default=2, help_text='Override capacity; 0 = unlimited. Auto-set from plan_name if left at default.'),
        ),
        migrations.CreateModel(
            name='ClinicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. عطلة عيد الأضحى', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_holidays_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinic Holiday',
                'verbose_name_plural': 'Clinic Holidays',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, help_text='e.g. إجازة سنوية، مؤتمر طبي', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_exceptions', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_exceptions_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Availability Exception',
                'verbose_name_plural': 'Doctor Availability Exceptions',
                'ordering': ['start_date'],
            },
        ),
    ]
