# Generated by Django 6.0.1 on 2026-03-02 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')])),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Clinic Working Hours',
                'verbose_name_plural': 'Clinic Working Hours',
                'ordering': ['weekday', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'weekday', 'start_time', 'end_time'), name='unique_clinic_working_hours')],
            },
        ),
    ]
