# Generated by Django 6.0.1 on 2026-02-28 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_specialties_clinic_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicactivationcode',
            name='used_by_clinic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_code', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='clinicstaff',
            name='role',
            field=models.CharField(choices=[('MAIN_DOCTOR', 'Main Doctor'), ('DOCTOR', 'Doctor'), ('SECRETARY', 'Secretary')], max_length=20),
        ),
    ]
