# Generated by Django 6.0.1 on 2026-03-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinicinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicinvitation',
            name='doctor_national_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinicinvitation',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('SECRETARY', 'Secretary')], default='DOCTOR', max_length=20),
        ),
    ]
