# Generated by Django 6.0.1 on 2026-03-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_plan_name_secretaries_holidays_exceptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicactivationcode',
            name='max_secretaries',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of secretaries allowed under this subscription.'),
        ),
        migrations.AlterField(
            model_name='clinicsubscription',
            name='max_secretaries',
            field=models.PositiveIntegerField(default=5, help_text='Override capacity; 0 = unlimited. Auto-set from plan_name if left at default.'),
        ),
    ]
