# Generated by Django 6.0.1 on 2026-03-05 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_add_doctor_national_id_to_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('CANCELLED', 'Cancelled'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_audit_logs', to='clinics.clinic')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='clinics.clinicinvitation')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation Audit Log',
                'verbose_name_plural': 'Invitation Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
