# Generated by Django 6.0.1 on 2026-02-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_clinicsubscription_and_activationcode_subscription_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicactivationcode',
            name='max_doctors',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of doctors allowed under this subscription.'),
        ),
        migrations.AlterField(
            model_name='clinicsubscription',
            name='max_doctors',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
