# Generated by Django 6.0.1 on 2026-04-01 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_fix_staff_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_families', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Drug Family',
                'verbose_name_plural': 'Drug Families',
                'ordering': ['name'],
                'unique_together': {('clinic', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DrugProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=255)),
                ('commercial_name', models.CharField(blank=True, max_length=255)),
                ('default_dosage', models.CharField(blank=True, max_length=100)),
                ('default_frequency', models.CharField(blank=True, max_length=100)),
                ('default_duration', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_products', to='clinics.clinic')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='clinics.drugfamily')),
            ],
            options={
                'verbose_name': 'Drug Product',
                'verbose_name_plural': 'Drug Products',
                'ordering': ['generic_name'],
            },
        ),
        migrations.CreateModel(
            name='OrderCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LAB', 'Lab'), ('RADIOLOGY', 'Radiology'), ('MICROBIOLOGY', 'Microbiology'), ('PROCEDURE', 'Procedure')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Order Catalog Item',
                'verbose_name_plural': 'Order Catalog Items',
                'ordering': ['category', 'name'],
                'unique_together': {('clinic', 'category', 'name')},
            },
        ),
    ]
