# Generated by Django 6.0.1 on 2026-05-08 18:45
#
# Note: New clinics get the model defaults (auto_confirm=True, allow_multiple_same_day=False).
# The data migration below backfills EXISTING clinics with allow_multiple_same_day=True
# to preserve current behavior — pre-existing clinics never had a same-day restriction,
# so flipping the default for them silently would be a behavior change.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_existing_clinic_settings(apps, schema_editor):
    Clinic = apps.get_model("clinics", "Clinic")
    ClinicBookingSettings = apps.get_model("clinics", "ClinicBookingSettings")
    for clinic in Clinic.objects.all():
        ClinicBookingSettings.objects.get_or_create(
            clinic=clinic,
            defaults={
                "auto_confirm_patient_bookings": True,
                "allow_multiple_bookings_same_day": True,
            },
        )


def remove_backfilled_settings(apps, schema_editor):
    ClinicBookingSettings = apps.get_model("clinics", "ClinicBookingSettings")
    ClinicBookingSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_order_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicBookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_confirm_patient_bookings', models.BooleanField(default=True, help_text='If True, patient self-bookings are CONFIRMED immediately. If False, they land as PENDING and need secretary approval.')),
                ('allow_multiple_bookings_same_day', models.BooleanField(default=False, help_text="If False, a patient's 2nd same-day self-booking lands as PENDING regardless of the auto-confirm setting.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_settings', to='clinics.clinic')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinic Booking Settings',
                'verbose_name_plural': 'Clinic Booking Settings',
            },
        ),
        migrations.RunPython(backfill_existing_clinic_settings, remove_backfilled_settings),
    ]
