# Generated by Django 6.0.1 on 2026-05-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_clinicbookingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicbookingsettings',
            name='no_show_after',
            field=models.CharField(choices=[('10m', '10 minutes'), ('15m', '15 minutes'), ('30m', '30 minutes'), ('1h', '1 hour'), ('2h', '2 hours'), ('4h', '4 hours'), ('6h', '6 hours'), ('1d', 'End of the appointment day')], default='1h', help_text="How long after the appointment start time an unattended appointment is auto-marked NO_SHOW. '1d' = once the appointment day has fully ended.", max_length=4),
        ),
    ]
