# Generated by Django 6.0.1 on 2026-06-22 14:18

import core.validators.file_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_clinicbookingsettings_no_show_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional clinic logo shown on printed documents.', null=True, upload_to='clinic_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'pdf']), core.validators.file_validators.validate_file_signature, core.validators.file_validators.validate_file_size]),
        ),
    ]
