# Generated by Django 6.0.1 on 2026-06-25 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_clinic_display_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPOINTMENT_CREATED', 'Appointment created'), ('APPOINTMENT_RESCHEDULED', 'Appointment rescheduled'), ('APPOINTMENT_STATUS_CHANGED', 'Appointment status changed'), ('APPOINTMENT_DELETED', 'Appointment deleted'), ('INVOICE_OPENED', 'Billing session opened'), ('INVOICE_CHARGE_ADDED', 'Charge added'), ('INVOICE_CHARGE_REMOVED', 'Charge removed'), ('INVOICE_DELETED', 'Invoice deleted'), ('PAYMENT_RECORDED', 'Payment recorded'), ('CLINICAL_NOTE_VIEWED', 'Clinical note viewed'), ('PATIENT_REGISTERED', 'Patient registered in clinic'), ('PATIENT_UPDATED', 'Patient record updated')], max_length=32)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['clinic', '-timestamp'], name='activity_clinic_time_idx'), models.Index(fields=['clinic', 'action'], name='activity_clinic_action_idx'), models.Index(fields=['target_type', 'target_id'], name='activity_target_idx')],
            },
        ),
    ]
