# Generated by Django 6.0.1 on 2026-03-16 19:30

import accounts.models
import core.validators.file_validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_identity_claims(apps, schema_editor):
    CustomUser = apps.get_model("accounts", "CustomUser")
    IdentityClaim = apps.get_model("accounts", "IdentityClaim")

    users = CustomUser.objects.exclude(national_id__isnull=True).exclude(national_id="")
    for user in users.iterator():
        national_id = "".join(ch for ch in str(user.national_id).strip() if ch.isdigit())
        if len(national_id) != 9:
            continue

        IdentityClaim.objects.get_or_create(
            user=user,
            national_id=national_id,
            status="VERIFIED",
            defaults={
                "verified_at": user.date_joined,
                "rejection_reason": "",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="national_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Verified/canonical national ID only. Pending claims live in IdentityClaim.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="IdentityClaim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("national_id", models.CharField(db_index=True, max_length=9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNVERIFIED", "Unverified"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="UNVERIFIED",
                        max_length=20,
                    ),
                ),
                ("evidence_file", models.FileField(blank=True, help_text="Optional evidence submitted for manual review.", null=True, upload_to=accounts.models.identity_claim_evidence_upload_path, validators=[core.validators.file_validators.validate_file_extension, core.validators.file_validators.validate_file_signature, core.validators.file_validators.validate_file_size])),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="identity_claims", to=settings.AUTH_USER_MODEL)),
                ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="identity_claim_reviews", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Identity Claim",
                "verbose_name_plural": "Identity Claims",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="identityclaim",
            index=models.Index(fields=["user", "status"], name="identity_claim_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="identityclaim",
            index=models.Index(fields=["national_id", "status"], name="identity_claim_nid_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="identityclaim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "VERIFIED")),
                fields=("national_id",),
                name="unique_verified_identity_claim_per_national_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="identityclaim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "VERIFIED")),
                fields=("user",),
                name="unique_verified_identity_claim_per_user",
            ),
        ),
        migrations.RunPython(backfill_identity_claims, migrations.RunPython.noop),
    ]
