# Generated by Django 6.0.1 on 2026-02-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pending_email',
            field=models.EmailField(blank=True, help_text='Temporary storage for email until verification is complete.', max_length=254, null=True),
        ),
    ]
