# Generated by Django 6.0.1 on 2026-03-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_identity_claims'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, help_text='رقم الهوية الوطنية الموثق فقط. الطلبات المعلقة محفوظة في سجل المطالبات.', max_length=20, null=True),
        ),
    ]
