# Generated by Django 6.0.1 on 2026-02-28 12:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PATIENT', 'Patient'), ('MAIN_DOCTOR', 'Main Doctor'), ('DOCTOR', 'Doctor'), ('SECRETARY', 'Secretary')], max_length=20), blank=True, default=list, help_text='All roles assigned to this user (a user may hold multiple roles simultaneously).'),
        ),
    ]
