# Generated by Django 6.0.1 on 2026-05-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='time_format',
            field=models.CharField(choices=[('24', '24-hour'), ('12', '12-hour (AM/PM)')], default='24', help_text='Preferred time-of-day display style across the secretary side.', max_length=2),
        ),
    ]
