# Generated by Django 6.0.1 on 2026-06-25 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_time_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mfa_device_salt',
            field=models.CharField(blank=True, default='', help_text="Per-user salt for 'remember this device' cookies. Rotating it revokes every trusted device (sign out other devices).", max_length=64),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='Whether the user has an active second factor (TOTP) on login.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mfa_enrolled_at',
            field=models.DateTimeField(blank=True, help_text='When the user completed MFA enrollment.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mfa_totp_secret',
            field=models.CharField(blank=True, default='', help_text='Fernet-encrypted TOTP shared secret. Never stored in plaintext.', max_length=255),
        ),
        migrations.CreateModel(
            name='StaffMfaBackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=128)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff MFA Backup Code',
                'verbose_name_plural': 'Staff MFA Backup Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'used_at'], name='mfa_backup_user_used_idx')],
            },
        ),
    ]
