"""
Django settings for clinic_website project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

# Load .env file
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, ".env"))

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "0") == "1"

# Feature Flag: Enforce Phone Verification
# Default to True (secure-by-default) if not set.
# Set ENFORCE_PHONE_VERIFICATION=0 in .env to disable.
ENFORCE_PHONE_VERIFICATION = os.environ.get("ENFORCE_PHONE_VERIFICATION", "1") == "1"

# Feature Flag: Enforce OTP Limits
# Default to True (secure-by-default) if not set.
# Set ENFORCE_OTP_LIMITS=0 in .env to disable daily limits (for dev/testing).
ENFORCE_OTP_LIMITS = os.environ.get("ENFORCE_OTP_LIMITS", "1") == "1"

# ============================================
# LOGIN BRUTE-FORCE THROTTLE (accounts/ratelimit.py)
# ============================================
# Per-account (phone) layer: N failures then an escalating block.
LOGIN_MAX_ATTEMPTS = int(os.environ.get("LOGIN_MAX_ATTEMPTS", "5"))
LOGIN_WINDOW_SECONDS = int(os.environ.get("LOGIN_WINDOW_SECONDS", "900"))
# Per-IP layer: higher cap, since one IP can legitimately be many users (NAT).
LOGIN_IP_MAX_ATTEMPTS = int(os.environ.get("LOGIN_IP_MAX_ATTEMPTS", "20"))
LOGIN_IP_WINDOW_SECONDS = int(os.environ.get("LOGIN_IP_WINDOW_SECONDS", "900"))

# ============================================
# REPORT / BULK-EXPORT GUARDS (secretary portal CSV reports)
# ============================================
# Max width (days) of a report date range; wider requests are clamped so one
# export can't scan/dump unbounded PHI history. ~1 year by default.
REPORT_MAX_RANGE_DAYS = int(os.environ.get("REPORT_MAX_RANGE_DAYS", "366"))
# Per-secretary bulk-export rate cap (accounts/ratelimit.export_rate_limited).
EXPORT_MAX_PER_WINDOW = int(os.environ.get("EXPORT_MAX_PER_WINDOW", "20"))
EXPORT_WINDOW_SECONDS = int(os.environ.get("EXPORT_WINDOW_SECONDS", "600"))

# ============================================
# SMS PROVIDER (TweetsMS)
# ============================================
SMS_PROVIDER = os.environ.get("SMS_PROVIDER", "")
TWEETSMS_API_KEY = os.environ.get("TWEETSMS_API_KEY", "")
TWEETSMS_SENDER = os.environ.get("TWEETSMS_SENDER", "")
TWEETSMS_BASE_URL = os.environ.get("TWEETSMS_BASE_URL", "https://tweetsms.ps/api.php")


ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")

# احتياط (اختياري): لو المتغير فاضي
if not ALLOWED_HOSTS or ALLOWED_HOSTS == [""]:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS", "http://localhost:8000"
).split(",")




# Application definition

INSTALLED_APPS = [
    "accounts",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "appointments",
    "patients",
    "doctors",
    "secretary",
    "clinics",
    "compliance",
    "rest_framework",
    "rest_framework_simplejwt",
    "django.contrib.postgres",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "accounts.middleware.LanguagePreferenceMiddleware",
    "clinics.middleware.ClinicIsolationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "clinic_website.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "clinics.context_processors.clinic_switcher",
                "appointments.context_processors.unread_notifications",
                "doctors.context_processors.doctor_context",
                "accounts.context_processors.language_context",
                "secretary.context_processors.time_format",
            ],
            "builtins": [
                "secretary.templatetags.clock_extras",
            ],
        },
    },
]

WSGI_APPLICATION = "clinic_website.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "db.sqlite3"),
        "USER": os.environ.get("DB_USER", ""),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# ============================================
# CACHE - REDIS
# ============================================
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL", "redis://127.0.0.1:6379"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ar"

LANGUAGES = [
    ("ar", "Arabic"),
    ("en", "English"),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

TIME_ZONE = "Asia/Gaza"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# Media files (Uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Custom User Model
AUTH_USER_MODEL = "accounts.CustomUser"

# ============================================
# AUTHENTICATION BACKENDS
# ============================================
# Custom authentication backend for phone number login
AUTHENTICATION_BACKENDS = [
    "accounts.backends.PhoneNumberAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Redirect to home URL after login
LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "/login/"

# ============================================
# DRF & JWT SETTINGS
# ============================================


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# ============================================
# SESSION SECURITY (staff portal handling PHI)
# Not HTTPS-dependent, so these apply in ALL environments. The Secure cookie
# flags (SESSION_COOKIE_SECURE / CSRF_COOKIE_SECURE) live in the `if not DEBUG`
# block below because they must stay off for local http dev.
#
# Backend: SESSION_ENGINE is unset -> django.contrib.sessions.backends.db.
# Sessions are server-side in the `django_session` table; the cookie carries
# only an opaque key, and auth.logout() flushes the record + cycles the key.
# ============================================

# Block JavaScript from reading the SESSION cookie (XSS cookie theft).
# This is already Django's default; set explicitly for auditability.
# NOTE: do NOT set CSRF_COOKIE_HTTPONLY — HTMX needs to read the csrftoken cookie.
SESSION_COOKIE_HTTPONLY = True

# Lock cross-site cookie behaviour. 'Lax' is Django's default; explicit for audit.
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Idle (rolling) timeout: 60 minutes of inactivity. SESSION_SAVE_EVERY_REQUEST
# re-stamps the expiry on every request, so the countdown resets on activity
# instead of being an absolute window from login.
SESSION_COOKIE_AGE = 3600  # 60 minutes
SESSION_SAVE_EVERY_REQUEST = True

# End the session when the browser is closed (defense for shared front-desk
# machines). The cookie becomes a browser-session cookie; the server-side idle
# timeout above still applies within an open browser.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ============================================
# PRODUCTION SECURITY HARDENING (HTTPS)
# Active only when DEBUG=False so local http dev is unaffected.
# ============================================
if not DEBUG:
    # App sits behind a trusted reverse proxy / load balancer that
    # terminates TLS and sets X-Forwarded-Proto. Only safe behind such a
    # proxy — never set this if the app is directly reachable.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Redirect every HTTP request to HTTPS.
    SECURE_SSL_REDIRECT = True

    # HTTP Strict Transport Security. 1 year + subdomains + preload is the
    # preload-list-eligible config. Consider ramping from a small value
    # (e.g. 3600) first if you are not yet certain all subdomains are HTTPS.
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookies only sent over HTTPS.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
