# Generated by Django 6.0.1 on 2026-02-18 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='doctors.doctorintakequestion'),
        ),
        migrations.AddField(
            model_name='appointmentattachment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentattachment',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='doctors.doctorintakequestion'),
        ),
        migrations.AddField(
            model_name='appointmentattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_types', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.appointmenttype'),
        ),
        migrations.AddConstraint(
            model_name='appointmentanswer',
            constraint=models.UniqueConstraint(fields=('appointment', 'question'), name='unique_answer_per_question_per_appointment'),
        ),
        migrations.AddConstraint(
            model_name='appointmenttype',
            constraint=models.UniqueConstraint(fields=('doctor', 'clinic', 'name'), name='unique_appointment_type_per_doctor_clinic'),
        ),
    ]
