# Generated by Django 6.0.1 on 2026-02-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttype',
            name='name_ar',
            field=models.CharField(blank=True, default='', help_text="Arabic name displayed to patients, e.g. 'فحص عام', 'متابعة', 'استشارة'", max_length=100),
        ),
    ]
