# Generated by Django 6.0.1 on 2026-03-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointmentnotification',
            name='unique_notification_per_appointment_type',
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether a reminder notification has been sent for this appointment.'),
        ),
        migrations.AddField(
            model_name='appointmentnotification',
            name='sent_via_email',
            field=models.BooleanField(default=False, help_text='True if an email was successfully sent for this notification.'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('CONFIRMED', 'مؤكد'), ('CHECKED_IN', 'وصل المريض'), ('IN_PROGRESS', 'جارٍ'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغى'), ('NO_SHOW', 'لم يحضر')], default='CONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentnotification',
            name='notification_type',
            field=models.CharField(choices=[('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_EDITED', 'Appointment Edited'), ('APPOINTMENT_BOOKED', 'Appointment Booked'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('APPOINTMENT_RESCHEDULED', 'Appointment Rescheduled'), ('APPOINTMENT_STATUS_CHANGED', 'Appointment Status Changed')], default='APPOINTMENT_CANCELLED', max_length=60),
        ),
    ]
