# Generated by Django 6.0.1 on 2026-02-21 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointmentnotification'),
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentnotification',
            name='cancelled_by_staff',
            field=models.ForeignKey(blank=True, help_text='ClinicStaff member who triggered this cancellation notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_notifications', to='clinics.clinicstaff'),
        ),
        migrations.AddConstraint(
            model_name='appointmentnotification',
            constraint=models.UniqueConstraint(fields=('appointment', 'notification_type'), name='unique_notification_per_appointment_type'),
        ),
    ]
