# Generated by Django 6.0.1 on 2026-03-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_add_doctor_clinic_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentnotification',
            name='context_role',
            field=models.CharField(choices=[('PATIENT', 'Patient Context'), ('DOCTOR', 'Doctor Context'), ('SECRETARY', 'Secretary Context')], default='PATIENT', help_text='The portal context this notification belongs to.', max_length=20),
        ),
    ]
