# Generated by Django 6.0.1 on 2026-02-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_notification_audit_and_uniqueconstraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnotification',
            name='notification_type',
            field=models.CharField(choices=[('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_EDITED', 'Appointment Edited')], default='APPOINTMENT_CANCELLED', max_length=40),
        ),
    ]
