# Generated by Django 6.0.1 on 2026-03-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointmentnotification_context_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnotification',
            name='context_role',
            field=models.CharField(choices=[('PATIENT', 'Patient Context'), ('DOCTOR', 'Doctor Context'), ('SECRETARY', 'Secretary Context'), ('CLINIC_OWNER', 'Clinic Owner Context')], default='PATIENT', help_text='The portal context this notification belongs to.', max_length=20),
        ),
    ]
