# Generated by Django 6.0.1 on 2026-02-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointmentnotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_edit_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the patient has edited this appointment. Max 2.'),
        ),
    ]
