# Generated by Django 6.0.1 on 2026-02-22 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007 appointmentattachment_file_group_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointmentnotification',
            name='unique_notification_per_appointment_type',
        ),
        migrations.DeleteModel(
            name='AppointmentNotification',
        ),
    ]
