# Generated by Django 6.0.1 on 2026-02-23 13:21

import appointments.models
import core.validators.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_remove_appointmentnotification_unique_notification_per_appointment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentattachment',
            name='file',
            field=models.FileField(upload_to=appointments.models.appointment_attachment_path, validators=[core.validators.file_validators.validate_file_signature, core.validators.file_validators.validate_file_size]),
        ),
    ]
