# Generated by Django 6.0.1 on 2026-02-23 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointmentattachment_file'),
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_EDITED', 'Appointment Edited')], default='APPOINTMENT_CANCELLED', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, help_text='Patient has read this notification.')),
                ('is_delivered', models.BooleanField(default=True, help_text='Always True for in-app notifications.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='appointments.appointment')),
                ('cancelled_by_staff', models.ForeignKey(blank=True, help_text='ClinicStaff member who triggered this cancellation notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_notifications', to='clinics.clinicstaff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment Notification',
                'verbose_name_plural': 'Appointment Notifications',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('appointment', 'notification_type'), name='unique_notification_per_appointment_type')],
            },
        ),
    ]
