# Generated by Django 6.0.1 on 2026-05-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_queue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentnotification',
            name='message_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appointmentnotification',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
