# Generated by Django 6.0.1 on 2026-02-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointmentnotification'),
        ('clinics', '0006_clinicverification'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointmenttype',
            name='unique_appointment_type_per_doctor_clinic',
        ),
        migrations.AddConstraint(
            model_name='appointmenttype',
            constraint=models.UniqueConstraint(fields=('clinic', 'name'), name='unique_appointment_type_per_clinic'),
        ),
        migrations.RemoveField(
            model_name='appointmenttype',
            name='doctor',
        ),
    ]
