# Generated by Django 6.0.1 on 2026-06-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_backfill_appointmentnotification_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentnotification',
            name='actor_name',
            field=models.CharField(blank=True, default='', help_text='Display name of the person who triggered this notification, denormalized at creation time so it survives appointment deletion.', max_length=255),
        ),
        migrations.AddField(
            model_name='appointmentnotification',
            name='actor_role',
            field=models.CharField(blank=True, choices=[('PATIENT', 'Patient'), ('SECRETARY', 'Secretary'), ('DOCTOR', 'Doctor')], default='', help_text='Role of the person who triggered this notification (for the actor badge). Blank for automatic/system events (e.g. reminders).', max_length=20),
        ),
    ]
