# Generated by Django 6.0.1 on 2026-06-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_appointmentnotification_actor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_note',
            field=models.TextField(blank=True, default='', help_text='Note from the secretary to the doctor (visible to the doctor + secretaries).'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='secretary_note',
            field=models.TextField(blank=True, default='', help_text='Note visible only to secretaries (written by the secretary at booking).'),
        ),
    ]
