# Generated by Django 6.0.1 on 2026-06-19 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_appointment_doctor_note_appointment_secretary_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentnotification',
            name='subject_patient',
            field=models.ForeignKey(blank=True, help_text='Patient this notification is about, used to route patient-scoped notifications (e.g. a profile note) when there is no appointment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointmentnotification',
            name='notification_type',
            field=models.CharField(choices=[('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_EDITED', 'Appointment Edited'), ('APPOINTMENT_BOOKED', 'Appointment Booked'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('APPOINTMENT_RESCHEDULED', 'Appointment Rescheduled'), ('APPOINTMENT_STATUS_CHANGED', 'Appointment Status Changed'), ('STAFF_NOTE_FOR_DOCTOR', 'Staff Note For Doctor'), ('STAFF_NOTE_FOR_SECRETARY', 'Staff Note For Secretary')], default='APPOINTMENT_CANCELLED', max_length=60),
        ),
    ]
