# Generated by Django 6.0.1 on 2026-06-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_appointmentnotification_subject_patient_and_more'),
        ('secretary', '0002_purchaserequest_purchaserequestitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentnotification',
            name='purchase_request',
            field=models.ForeignKey(blank=True, help_text='Purchase request this notification is about, used to route procurement notifications that have no associated appointment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='secretary.purchaserequest'),
        ),
        migrations.AlterField(
            model_name='appointmentnotification',
            name='notification_type',
            field=models.CharField(choices=[('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_EDITED', 'Appointment Edited'), ('APPOINTMENT_BOOKED', 'Appointment Booked'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('APPOINTMENT_RESCHEDULED', 'Appointment Rescheduled'), ('APPOINTMENT_STATUS_CHANGED', 'Appointment Status Changed'), ('STAFF_NOTE_FOR_DOCTOR', 'Staff Note For Doctor'), ('STAFF_NOTE_FOR_SECRETARY', 'Staff Note For Secretary'), ('PURCHASE_REQUEST_SUBMITTED', 'Purchase Request Submitted'), ('PURCHASE_REQUEST_APPROVED', 'Purchase Request Approved'), ('PURCHASE_REQUEST_REJECTED', 'Purchase Request Rejected')], default='APPOINTMENT_CANCELLED', max_length=60),
        ),
    ]
