# Generated by Django 6.0.1 on 2026-06-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_appointmentnotification_purchase_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnotification',
            name='actor_role',
            field=models.CharField(blank=True, choices=[('PATIENT', 'Patient'), ('SECRETARY', 'Secretary'), ('DOCTOR', 'Doctor'), ('OWNER', 'Owner')], default='', help_text='Role of the person who triggered this notification (for the actor badge). Blank for automatic/system events (e.g. reminders).', max_length=20),
        ),
    ]
