# Generated by Django 6.0.6 on 2026-07-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_alter_appointmentnotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentnotification',
            name='notification_type',
            field=models.CharField(choices=[('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_EDITED', 'Appointment Edited'), ('APPOINTMENT_BOOKED', 'Appointment Booked'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('APPOINTMENT_RESCHEDULED', 'Appointment Rescheduled'), ('APPOINTMENT_STATUS_CHANGED', 'Appointment Status Changed'), ('STAFF_NOTE_FOR_DOCTOR', 'Staff Note For Doctor'), ('STAFF_NOTE_FOR_SECRETARY', 'Staff Note For Secretary'), ('PURCHASE_REQUEST_SUBMITTED', 'Purchase Request Submitted'), ('PURCHASE_REQUEST_APPROVED', 'Purchase Request Approved'), ('PURCHASE_REQUEST_REJECTED', 'Purchase Request Rejected'), ('DOCTOR_REVIEW_RECEIVED', 'Doctor Review Received'), ('DEBT_UPDATED', 'Debt Updated')], default='APPOINTMENT_CANCELLED', max_length=60),
        ),
    ]
