# Generated by Django 6.0.1 on 2026-06-28 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0012_activitylog_report_exported'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text="Name shown to doctors/owners, e.g. 'Free' or 'Smart'.", max_length=100)),
                ('openrouter_model_id', models.CharField(help_text="OpenRouter model slug, e.g. 'anthropic/claude-sonnet-4.6' or a no-cost model like 'meta-llama/llama-3.3-70b-instruct:free'.", max_length=200)),
                ('is_free', models.BooleanField(default=False, help_text="If checked, using this model does NOT consume a doctor's monthly budget. Pair it with an actually-free OpenRouter model (…:free) so it also costs you nothing.")),
                ('is_active', models.BooleanField(default=True, help_text='Inactive models are hidden everywhere.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('input_price_per_mtok', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('output_price_per_mtok', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(blank=True, default='', max_length=100)),
                ('openrouter_model_id', models.CharField(blank=True, default='', max_length=200)),
                ('period', models.CharField(max_length=7)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('was_free', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('ERROR', 'Error')], default='OK', max_length=10)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage', to='ai_scribe.aimodel')),
            ],
            options={
                'verbose_name': 'AI Usage Record',
                'verbose_name_plural': 'AI Usage Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'doctor', 'period'], name='ai_scribe_a_clinic__076a4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DoctorClinicAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Master on/off for AI scribe for this doctor at this clinic.')),
                ('monthly_limit_usd', models.DecimalField(decimal_places=2, default=0, help_text='Monthly USD cap for paid models (resets on the 1st). The Free model is never capped.', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_models', models.ManyToManyField(blank=True, help_text='Models this doctor may choose from.', related_name='allowed_for_configs', to='ai_scribe.aimodel')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_doctor_configs', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_configs_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(limit_choices_to={'role__in': ['DOCTOR', 'MAIN_DOCTOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='ai_clinic_configs', to=settings.AUTH_USER_MODEL)),
                ('selected_model', models.ForeignKey(blank=True, help_text="The doctor's currently-chosen model (must be within allowed_models).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_configs', to='ai_scribe.aimodel')),
            ],
            options={
                'verbose_name': 'Doctor Clinic AI Config',
                'verbose_name_plural': 'Doctor Clinic AI Configs',
                'constraints': [models.UniqueConstraint(fields=('clinic', 'doctor'), name='unique_ai_config_per_doctor_clinic')],
            },
        ),
        migrations.CreateModel(
            name='DoctorMonthlySpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text="Calendar month, 'YYYY-MM'.", max_length=7)),
                ('spent_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_monthly_spend', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_monthly_spend', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Monthly AI Spend',
                'verbose_name_plural': 'Doctor Monthly AI Spend',
                'indexes': [models.Index(fields=['clinic', 'doctor', 'period'], name='ai_scribe_d_clinic__09d4af_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'doctor', 'period'), name='unique_ai_spend_per_doctor_clinic_period')],
            },
        ),
    ]
