# Generated by Django 6.0.1 on 2026-02-23 13:21

import core.validators.file_validators
import django.core.validators
import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=patients.models.PatientProfile.get_avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'pdf']), core.validators.file_validators.validate_file_signature, core.validators.file_validators.validate_file_size]),
        ),
    ]
