# Generated by Django 6.0.1 on 2026-04-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_clinicalnote_extra_sections_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnote',
            name='extra_sections_labels',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
