# Generated by Django 6.0.1 on 2026-06-19 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_appointmentnotification_subject_patient_and_more'),
        ('clinics', '0008_clinicbookingsettings_no_show_after'),
        ('patients', '0008_alter_clinicalnote_extra_sections_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('DOCTOR', 'Doctor'), ('SECRETARY', 'Secretary')], max_length=20)),
                ('body', models.TextField()),
                ('author_name', models.CharField(blank=True, default='', help_text="Display name of the author, denormalized so the note survives the author's deletion.", max_length=255)),
                ('author_role', models.CharField(blank=True, default='', help_text='Role of the author at write time (e.g. SECRETARY).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Set when the note is attached to a specific appointment; None for a patient-profile note.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_notes', to='appointments.appointment')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notes', to='clinics.clinic')),
                ('patient', models.ForeignKey(help_text='The patient this note is about.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_notes_about', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Note',
                'verbose_name_plural': 'Staff Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
