# Generated by Django 6.0.1 on 2026-06-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_staffnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffnote',
            name='audience',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('SECRETARY', 'Secretary'), ('DOCTOR_PRIVATE', 'Doctor (private)')], max_length=20),
        ),
    ]
