# Generated by Django 6.0.1 on 2026-06-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_clinicalnoteaddendum'),
        ('patients', '0010_alter_staffnote_audience'),
    ]

    operations = [
    ]
