# Generated by Django 6.0.1 on 2026-06-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_merge_20260620_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='is_secretary_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
