# Generated by Django 6.0.1 on 2026-06-25 15:34

import core.validators.file_validators
import django.core.validators
import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_clinicalnote_is_secretary_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='file',
            field=models.FileField(upload_to=patients.models._record_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'pdf']), core.validators.file_validators.validate_file_signature, core.validators.file_validators.validate_file_size]),
        ),
    ]
