# Generated by Django 6.0.1 on 2026-06-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_medicalrecord_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='allergy_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='allergy_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
