# Generated by Django 6.0.1 on 2026-02-18 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(help_text='Arabic name for display to patients.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='DoctorForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_forms', to='clinics.clinic')),
                ('doctor', models.ForeignKey(limit_choices_to={'role__in': ['DOCTOR', 'MAIN_DOCTOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='intake_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Intake Form (Legacy)',
                'verbose_name_plural': 'Doctor Intake Forms (Legacy)',
            },
        ),
        migrations.CreateModel(
            name='DoctorIntakeFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Instructions displayed before the form.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_type', models.ForeignKey(blank=True, help_text='If set, form only appears for this type. NULL = all types.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_form_templates', to='appointments.appointmenttype')),
                ('doctor', models.ForeignKey(limit_choices_to={'role__in': ['DOCTOR', 'MAIN_DOCTOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='intake_form_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intake Form Template',
                'verbose_name_plural': 'Intake Form Templates',
                'ordering': ['doctor', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorIntakeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='English question text.', max_length=500)),
                ('question_text_ar', models.CharField(blank=True, default='', help_text='Arabic question text.', max_length=500)),
                ('field_type', models.CharField(choices=[('TEXT', 'نص قصير'), ('TEXTAREA', 'نص طويل'), ('SELECT', 'قائمة منسدلة'), ('MULTISELECT', 'اختيار متعدد'), ('CHECKBOX', 'مربع اختيار (نعم/لا)'), ('DATE', 'تاريخ'), ('FILE', 'ملف مرفق')], default='TEXT', max_length=20)),
                ('choices', models.JSONField(blank=True, default=list, help_text='For SELECT/MULTISELECT: ["opt1", "opt2"].')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text_content', models.TextField(blank=True, db_column='help_text_content')),
                ('max_file_size_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('allowed_extensions', models.JSONField(blank=True, default=list, help_text='e.g. ["pdf", "jpg", "png"].')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='doctors.doctorintakeformtemplate')),
            ],
            options={
                'verbose_name': 'Intake Question',
                'verbose_name_plural': 'Intake Questions',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DoctorIntakeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_value', models.CharField(max_length=500)),
                ('operator', models.CharField(choices=[('EQUALS', 'يساوي'), ('NOT_EQUALS', 'لا يساوي'), ('CONTAINS', 'يحتوي'), ('IN', 'ضمن القائمة')], default='EQUALS', max_length=20)),
                ('action', models.CharField(choices=[('SHOW', 'أظهر'), ('HIDE', 'أخفِ')], default='SHOW', max_length=10)),
                ('source_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_as_source', to='doctors.doctorintakequestion')),
                ('target_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_as_target', to='doctors.doctorintakequestion')),
            ],
            options={
                'verbose_name': 'Intake Rule',
                'verbose_name_plural': 'Intake Rules',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Public bio displayed on the booking page.')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role__in': ['DOCTOR', 'MAIN_DOCTOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('field_type', models.CharField(choices=[('TEXT', 'نص قصير'), ('TEXTAREA', 'نص طويل'), ('NUMBER', 'رقم'), ('SINGLE_CHOICE', 'اختيار واحد'), ('MULTI_CHOICE', 'اختيار متعدد'), ('BOOLEAN', 'نعم / لا')], default='TEXT', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='doctors.doctorform')),
            ],
            options={
                'verbose_name': 'Form Field (Legacy)',
                'verbose_name_plural': 'Form Fields (Legacy)',
                'ordering': ['form', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialties', to='doctors.doctorprofile')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialties', to='doctors.specialty')),
            ],
            options={
                'verbose_name': 'Doctor Specialty',
                'verbose_name_plural': 'Doctor Specialties',
            },
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='doctors', through='doctors.DoctorSpecialty', to='doctors.specialty'),
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_availabilities', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Availability',
                'verbose_name_plural': 'Doctor Availabilities',
                'ordering': ['day_of_week', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'clinic', 'day_of_week', 'start_time'), name='unique_doctor_clinic_day_start')],
            },
        ),
        migrations.AddConstraint(
            model_name='doctorform',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('doctor', 'clinic'), name='unique_active_form_per_doctor_clinic'),
        ),
        migrations.AddConstraint(
            model_name='doctorintakeformtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('doctor', 'appointment_type'), name='unique_active_intake_per_doctor_type'),
        ),
        migrations.AddConstraint(
            model_name='doctorintakequestion',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='unique_question_order_per_template'),
        ),
        migrations.AddConstraint(
            model_name='doctorintakerule',
            constraint=models.UniqueConstraint(fields=('source_question', 'target_question', 'expected_value'), name='unique_intake_rule'),
        ),
        migrations.AddConstraint(
            model_name='doctorintakerule',
            constraint=models.CheckConstraint(condition=models.Q(('source_question', models.F('target_question')), _negated=True), name='intake_rule_no_self_reference'),
        ),
        migrations.AddConstraint(
            model_name='doctorspecialty',
            constraint=models.UniqueConstraint(fields=('doctor_profile', 'specialty'), name='unique_doctor_specialty'),
        ),
        migrations.AddConstraint(
            model_name='doctorspecialty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('doctor_profile',), name='unique_primary_specialty_per_doctor'),
        ),
    ]
