# Generated by Django 6.0.1 on 2026-02-12 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(help_text='Arabic name for display to patients.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this specialty.')),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Public bio displayed on the booking page.')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, help_text='Number of years of medical practice.', null=True)),
                ('user', models.OneToOneField(limit_choices_to={'role__in': ['DOCTOR', 'MAIN_DOCTOR']}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Profile',
                'verbose_name_plural': 'Doctor Profiles',
            },
        ),
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text="Is this the doctor's primary specialty?")),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialties', to='doctors.doctorprofile')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialties', to='doctors.specialty')),
            ],
            options={
                'verbose_name': 'Doctor Specialty',
                'verbose_name_plural': 'Doctor Specialties',
            },
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='doctors', through='doctors.DoctorSpecialty', to='doctors.specialty'),
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True, help_text='Temporarily disable this slot without deleting it.')),
                ('clinic', models.ForeignKey(help_text='The clinic where this availability applies.', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_availabilities', to='clinics.clinic')),
                ('doctor', models.ForeignKey(help_text='The doctor this availability belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Availability',
                'verbose_name_plural': 'Doctor Availabilities',
                'ordering': ['day_of_week', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'clinic', 'day_of_week', 'start_time'), name='unique_doctor_clinic_day_start')],
            },
        ),
        migrations.AddConstraint(
            model_name='doctorspecialty',
            constraint=models.UniqueConstraint(fields=('doctor_profile', 'specialty'), name='unique_doctor_specialty'),
        ),
        migrations.AddConstraint(
            model_name='doctorspecialty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('doctor_profile',), name='unique_primary_specialty_per_doctor'),
        ),
    ]
