# Generated by Django 6.0.1 on 2026-03-11 18:41

import django.db.models.deletion
import doctors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_doctor_onboarding'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_status', models.CharField(choices=[('IDENTITY_UNVERIFIED', 'Unverified'), ('IDENTITY_PENDING_REVIEW', 'Pending Review'), ('IDENTITY_VERIFIED', 'Verified'), ('IDENTITY_REJECTED', 'Rejected'), ('IDENTITY_REVOKED', 'Revoked')], default='IDENTITY_UNVERIFIED', max_length=30)),
                ('identity_document', models.FileField(blank=True, help_text='Government-issued ID (National ID, Passport).', null=True, upload_to=doctors.models._doctor_id_upload_path)),
                ('medical_license', models.FileField(blank=True, help_text='Medical practice license / certificate.', null=True, upload_to=doctors.models._doctor_license_upload_path)),
                ('identity_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('identity_rejection_reason', models.TextField(blank=True, default='', help_text='Admin-provided reason when identity is rejected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_reviews_performed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Verification',
                'verbose_name_plural': 'Doctor Verifications',
            },
        ),
        migrations.CreateModel(
            name='ClinicDoctorCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_status', models.CharField(choices=[('CREDENTIALS_PENDING', 'Pending'), ('CREDENTIALS_VERIFIED', 'Verified'), ('CREDENTIALS_REJECTED', 'Rejected'), ('CREDENTIALS_REVOKED', 'Revoked')], default='CREDENTIALS_PENDING', max_length=30)),
                ('specialty_certificate', models.FileField(blank=True, help_text='Specialty certification document (if applicable).', null=True, upload_to=doctors.models._credential_upload_path)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_credentials', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_credentials', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_reviews_performed', to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinic_credentials', to='doctors.specialty')),
            ],
            options={
                'verbose_name': 'Clinic Doctor Credential',
                'verbose_name_plural': 'Clinic Doctor Credentials',
                'constraints': [models.UniqueConstraint(fields=('doctor', 'clinic', 'specialty'), name='unique_credential_per_doctor_clinic_specialty')],
            },
        ),
    ]
