# Generated by Django 6.0.1 on 2026-04-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_remove_unique_together_add_custom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnotetemplateelement',
            name='element_type',
            field=models.CharField(choices=[('SUBJECTIVE', 'S — Subjective'), ('OBJECTIVE', 'O — Objective'), ('ASSESSMENT', 'A — Assessment'), ('PLAN', 'P — Plan'), ('FREE_TEXT', 'Free Text'), ('VITALS', 'Vitals'), ('BODY_DIAGRAM', 'Body Diagram'), ('DENTAL', 'Dental Chart'), ('CUSTOM', 'Custom Section')], max_length=20),
        ),
    ]
