# Generated by Django 6.0.1 on 2026-05-01 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_order_catalog'),
        ('doctors', '0007_alter_clinicalnotetemplateelement_element_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorFavouriteDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='clinics.drugproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_drugs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Favourite Drug',
                'verbose_name_plural': 'Doctor Favourite Drugs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'drug_product'], name='doctors_doc_user_id_1f38a1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'drug_product'), name='unique_doctor_favourite_drug')],
            },
        ),
    ]
