# Generated by Django 6.0.1 on 2026-06-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_doctorreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreview',
            name='doctor_response',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='doctorreview',
            name='doctor_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
